[package]
name = "wallpaper-downloader"
version = "0.1.0"
edition = "2021"
description = "Download and organize wallpapers from Basic Apple Guy"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "6"
shellexpand = "3"
reqwest = { version = "0.13.3" }
scraper = "0.27"
serde = { version = "1", features = ["derive"] }
toml = "1.1.2+spec-1.1.0"
indicatif = "0.18.4"
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "fs",
] }